pipeline:
  publish:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: drone:5000/cicd-idpw0
    registry: drone:5000
    insecure: true
    tags: "${DRONE_BUILD_NUMBER}"
    environment:
      - version=${DRONE_BUILD_NUMBER}
  deploy:
    image: ciscodevnet/drone-iox-deploy-img
    commands:
      - python /deploy2FogD.py
    environment:
      - imageTag=${DRONE_BUILD_NUMBER}
      - dockerReg=10.10.20.25:5000
      - appname=drone:cicd-idpw1